### ISSUE TITLE
discussion_count is not available inside a essay

### ISSUE THREAD

**Issue by BlackSkorpio** [koken/issues#1]
It's not possible to use the `<koken:discussion_count>{{ discussion_count }}</koken:discussion_count>` inside a essay(/page?) as of today.
(Koken 0.21.13)

**Comment by MikeCostello** [comment]
Fixed in plugin v1.2.2 https://github.com/koken/koken-disqus/commit/d1135f6428fcb4405d9c9a551b4ead8114f6f0b7
