### ISSUE TITLE
Option to display album and set name in Library console

### ISSUE THREAD

**Issue by BlackSkorpio** [koken/issues#10]
Instead of only showing the album/set id: adding the album/set name will make the Library even more user-friendly.
It can today be archived with the help of a third-party plugin: https://github.com/DanielMuller/koken-plugin-library_display

But I believe it would be better to add this functionality directly to the core

**Comment by MikeCostello** [comment]
The thumbnail text is controlled by the Sort control. When set to "Title" the text will be displayed below the thumbnails. Manual (default) displays the ordinal index. The tooltip is always set to the Title.

![sort](https://cloud.githubusercontent.com/assets/1423247/13083234/1bd0678a-d4a2-11e5-953c-ca22b056ad70.png)
