### ISSUE TITLE
The word comments in discussion_count is hard coded

### ISSUE THREAD

**Issue by BlackSkorpio** [koken/issues#14]
When using `{{ discussion_count }}` the output is **x Comments** no matter what language is set in the theme settings panel.

> _OFF TOPIC_
> And as a side note IMO we can "lose" the "Comments" all toghter and only display the number

**Comment by MikeCostello** [comment]
As best I can tell Disqus only allows customization of the count format via their [control panel](https://help.disqus.com/customer/portal/articles/565624-adding-comment-count-links-to-your-home-page) (last section of article), but not their API.

**Comment by BlackSkorpio** [comment]
Ahhh, you once again "got me" on this one @MikeCostello ;)
