### ISSUE TITLE
Font Awesome is "out-dated"

### ISSUE THREAD

**Issue by BlackSkorpio** [koken/issues#2]
The included Font Awesome is outdated and need to be updated.
- Included: Font Awesome 3.0.1
- Current: Font Awesome 4.5.0
  (Koken 0.21.13)

**Comment by MikeCostello** [comment]
upgraded in v0.21.14 https://github.com/koken/koken/commit/5d5f5348ba16250a6999b3c58173f29af9c5f1c9
