### ISSUE TITLE
Koken:asset breaks when versioning JS

### ISSUE THREAD

**Issue by BlackSkorpio** [koken/issues#20]
Enviroment: latest Koken

Using `<koken:asset file="inc/js/main.min.js?2.3" />` will make Koken not recognize the javascript: dues not including it at all.

**Comment by MikeCostello** [comment]
Added a new `version` parameter to `koken:asset` in v0.22.13-beta.6. If set to `true` the theme's version number will be used as a cache buster or if set to a _string_ then that string will be used instead.
