### ISSUE TITLE
koken:permalink is broken in 22.5

### ISSUE THREAD

**Issue by BlackSkorpio** [koken/issues#23]
The `<koken:permalink />` that is used in the RSS feeds is broken.
On line 1861 in koken.php we have:

```
$url = $protocol . '//' . $_SERVER['HTTP_HOST'] . $url;
```

It should instead say:

```
$url = $protocol . '://' . $_SERVER['HTTP_HOST'] . $url;
```

Issue reported at [KCS](https://kokensupport.com/viewtopic.php?f=8&t=427) (we have provided [a quick DIY fix](https://kokensupport.com/viewtopic.php?p=1931#p1933) for the time being) and [help.koken.me](http://help.koken.me/customer/portal/questions/16326974-koken-rss-feeds-not-validating)

**Comment by MikeCostello** [comment]
Fixed in v0.22.6-beta.2   https://github.com/koken/koken/commit/1df356fde8050d55ddd563f16e22561254493926
