### ISSUE TITLE
Don't ask people to downgrade PHP on their server

### ISSUE THREAD

**Issue by beverloo** [koken/issues#27]
During installation, the following message will be displayed when running PHP 7:

> Koken is incompatible with PHP 7. Ask your host or system administrator to downgrade to PHP 5.3 to 5.6

This is absolutely terrible advice— you should not tell people to _downgrade_ software on their servers. In addition, PHP versions older than 5.6 are officially unsupported.

Please consider replacing this with a message that says that PHP 7 compatibility has not been fully assessed yet, maybe with a link to a help article sharing more details. Or, ideally, finish the assessment.

**Comment by BlackSkorpio** [comment]
Belive this one can be closed by now?
