### ISSUE TITLE
Not possible to turn lazy loading on and of via theme settings

### ISSUE THREAD

**Issue by BlackSkorpio** [koken/issues#29]
When trying to use `lazy="{{ settings.use_lazy }}"` and creating a toggle in the theme settings panel.
Lazy loading always will return false
It doesn't matter if I use

```
                "use_lazy": {
                    "label": "Use lazy loading",
                    "type": "boolean",
                    "values": { "true": "true", "false": "false" },
                    "value": "false",
                    "control_first": true
                },
```

Or:

```
                "use_lazy": {
                    "label": "Use lazy loading",
                    "type": "boolean",
                    "value": "true",
                    "control_first": true
                },
```

As soon as  `lazy="true"` is changed to  `lazy="{{ settings.use_lazy }}"` lazy loading fails

**Comment by MikeCostello** [comment]
The `lazy` parameter doesn't accept dynamic binding, but you can use `<koken:if true="{{ settings.use_lazy }}">`
