### ISSUE TITLE
koken:link to="custom" do not work

### ISSUE THREAD

**Issue by BlackSkorpio** [koken/issues#3]
Using `<koken:link to="custom">My custom template</koken:link>` Dosent work.
Tested after adding routes and templates for it inside the theme info.json 
(Koken version 0.21.13)

**Comment by MikeCostello** [comment]
[fixed](https://github.com/koken/koken/commit/a37bd08162c5227dd3c013d37ec538150c2f414e) in v0.21.14 using `<koken:link to="custom">` syntax
