### ISSUE TITLE
Geolocation & SSL issue

### ISSUE THREAD

**Issue by stupalov** [koken/issues#31]
https://kokensupport.com/viewtopic.php?t=490

Google geolocation API not work on https sites.

When I try to click "geo icon" (in right Inspector pane) nothing happened.
In Chrome Developer I see errors:

`Mixed Content: The page at 'https://stupalov.com/admin/#/library/albums/2/content/selection:5' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://maps.googleapis.com/maps/api/geocode/json?latlng=59.976845,30.302836666667&sensor=false'. This request has been blocked; the content must be served over HTTPS.`

`XMLHttpRequest cannot load http://maps.googleapis.com/maps/api/geocode/json?latlng=59.976845,30.302836666667&sensor=false. Failed to start loading.`

I know that Google Api requires serve https requests when site use https.

**Comment by MikeCostello** [comment]
This will be fixed in the next release.
