### ISSUE TITLE
login.lens's body tag has no helper class like "k-lens-login"

### ISSUE THREAD

**Issue by Hard-One** [koken/issues#34]
While using Password Protect plugin, the body tag in login.lens has no helper class named k-lens-login.

From reading the docs at http://help.koken.me/customer/portal/articles/828695-helper-classes it should be added to the page automagically.

**Comment by MikeCostello** [comment]
Does this occur on a custom theme? If so, when a theme overloads the plugin template it must provide its own `<body>` element classes.

**Comment by BlackSkorpio** [comment]
Yes, from what I seen it's only when a theme has it's own login.lens

**Comment by MikeCostello** [comment]
This should be fixed in v0.22.13-beta.4
