### ISSUE TITLE
exif.lens returns empty in admin

### ISSUE THREAD

**Issue by BlackSkorpio** [koken/issues#36]
The tag `{{ exif.lens }}` will always return empty when viewed inside admin, but on live site it behaves as expected.

**Comment by BlackSkorpio** [comment]
Sorry to say that this is _not limited_ to admin, `{{ exif.lens }}` returns empty outside of any template besides content.lens

**Comment by MikeCostello** [comment]
Triggered by having two koken:exif tags in the same template. Testing a fix in v0.22.13-beta.3

**Comment by BlackSkorpio** [comment]
Looks as the fix is working
