### ISSUE TITLE
Koken Installer varintId 

### ISSUE THREAD

**Issue by sscholl** [koken/issues#37]
The installer throws an error:

> Uncaught ReferenceError: intId is not defined

The variable intId is not set because a whitespace is missing in line 774.

`varintId = setInterval(function() {`
`var intId = setInterval(function() {`

**Comment by MikeCostello** [comment]
Thank you for reporting, the tab whitespace has been replaced with a space. fixed https://github.com/koken/koken-installer/commit/83b0893b528d9eb3125cc60591ce4d1730076cc7
