### ISSUE TITLE
<koken:time /> produces a trailing 0 when used with themes that use language select

### ISSUE THREAD

**Issue by BlackSkorpio** [koken/issues#4]
The use of `<koken:time />` in conjunction with with custom date format for example: `jS F Y` will output a trailing 0 after `j`.

This only affects theme that uses the language feature of koken

**Comment by BlackSkorpio** [comment]
Steps to reproduce this behavior use `jS F Y` as date format in any premium theme

**Comment by MikeCostello** [comment]
fixed in v0.21.14 https://github.com/koken/koken/commit/c040a7fe8826d943e090ee681e3bd27edd70ffc3

There are no ordinal suffixes for [international date formatting](http://www.icu-project.org/apiref/icu4c/classSimpleDateFormat.html#details). Use of `S` restricted to `en` languages.

**Comment by MikeCostello** [comment]
Reverted https://github.com/koken/koken/commit/c040a7fe8826d943e090ee681e3bd27edd70ffc3

**Comment by MikeCostello** [comment]
More scoped fix for 'S' english ordinal suffix https://github.com/koken/koken/commit/7c295008e04eb2e05b8ef5cbbc5b1e7bf0124bb7
