### ISSUE TITLE
IPTC value for Copyright is empty

### ISSUE THREAD

**Issue by humantex** [koken/issues#40]
When inserting a koken:not lens tag call for IPTC copyright in a template, it doesn't return a value to the page.

```
<koken:not empty="exif.iso_speed_ratings">
	<li>
		<span class="label">ISO</span>
		<span class="value">{{ exif.iso_speed_ratings }}</span>
	</li>
</koken:not>
<koken:not empty="iptc.copyright">
	<li>
		<span class="label">Copyright</span>
		<span class="value">{{ iptc.copyright }}</span>
	</li>
</koken:not>
```
![koken_iptc-copyright](https://cloud.githubusercontent.com/assets/16087649/20094772/be1c8bb4-a570-11e6-8e91-bd7c37aa0fe9.jpg)

**Comment by BlackSkorpio** [comment]
@humantex have you tried wrapping it inside `<koken:iptc>`

```
<koken:iptc>
    <koken:not empty="iptc.copyright">
        <li><span class="label">Copyright</span> <span class="value">{{ iptc.copyright }}</span></li>
    </koken:not>
</koken:iptc>
```

**Comment by humantex** [comment]
I just tried your suggestion Bjarne (Thanks)... but unfortunately I got the same result with an image that I know has the embedded value as served by Apache.

I'm using a heavily modified copy of the Elementary theme and am adding in a few more value pairs from what was already in the original Koken-released version. I've used the same pattern that it did and all the pairs I've added to my version are returning results so far - except for this one.

I haven't tried any other IPTC values, so I don't know if this is a one-off problem with koken:not whenever it's used with just this key, or if it applies to the whole IPTC group. According to the API notes on [Koken's lens tags page](http://help.koken.me/customer/portal/articles/828690-lens-tags#kokennot) the 'koken:not' attribute is available globally, and has certainly worked for me on every other tag I've used it on up to now.

Attached is a fresh screen grab with my last additions, and no itpc.copyright is displayed (should be showing at the arrow.

![koken_iptc-copyright-2](https://cloud.githubusercontent.com/assets/16087649/20243092/086f5a5e-a916-11e6-8bab-0c75353f96c4.jpg)
)

**Comment by BlackSkorpio** [comment]
Hmmm, sure sounds odd
But it's better to discuss this over at the forum: https://kokensupport.com

(If you hop over to the forum, please supply a link to a image that you know have the itpc.copyright set for debugging purpose)

**Comment by MikeCostello** [comment]
Can we confirm the image has an IPTC Copyright Notice field? I tried this with the attached image and the code @BlackSkorpio suggested worked.

![bike](https://cloud.githubusercontent.com/assets/1423247/21055695/87c7c698-be00-11e6-9870-0bc157f8c8b2.jpg)

**Comment by humantex** [comment]
I just switched hosting providers to ones that provide full ImageMagick support and have begun to populate the site, so I now have a working example publicly available. Here's a direct link to an image with the IPTC info embedded... https://lumiworx.com/storage/originals/f7/ba/mapleWide-bw.jpg

The copyright info does indeed show in the back-end when clicking the 'view' link for IPTC, but the code doesn't get included as part of the front-end page display. The Album/Image page is here: https://lumiworx.com/albums/nature-photography/content/straight-up-maple/

Here's the entire code block I use for EXIF/IPTC display within my theme's "content.lens" file, including it's surrounding 'koken:if' entries:

```
<koken:if true="settings.content_detail_show_exif">

<koken:exif>

<section>

  <!-- EXIF Accordian - start block -->
	<nav class="exif-accordion arrows">
		<header class="exif-box">
			<label for="acc-close" class="exif-box-title">EXIF Data</label>
		</header>
		<input type="radio" name="exif-accordion" id="cb1" />
		<section class="exif-box">
			<label class="exif-box-title" for="cb1">View</label>
			<label class="exif-box-close" for="acc-close"></label>
			<div class="exif-box-content">
      <!-- EXIF Accordian - start block END -->      
            
             
					<ol class="data"> 
          <koken:not empty="exif.make">
						<li>
							<span class="label">Camera/Device</span>
							<span class="value">{{ exif.make }}</span>
						</li>
					</koken:not>          
					<koken:not empty="exif.model">
						<li>
							<span class="label">Model</span>
							<span class="value">{{ exif.model }}</span>
						</li>
					</koken:not>
          <koken:not empty="exif.lens">
          	<li>
          		<span class="label">Lens</span>
          		<span class="value">{{ exif.lens }}</span>
          	</li>
          </koken:not> 
					<koken:not empty="exif.focal_length">
						<li>
							<span class="label">Focal length</span>
							<span class="value">{{ exif.focal_length }}</span>
						</li>
					</koken:not>                    
					<koken:not empty="exif.aperture">
						<li>
							<span class="label">Aperture</span>
							<span class="value">{{ exif.aperture }}</span>
						</li>
					</koken:not>
          <koken:not empty="exif.flash">
          	<li>
          		<span class="label">Flash</span>
          		<span class="value">{{ exif.flash }}</span>
          	</li>
          </koken:not>
					<koken:not empty="exif.iso_speed_ratings">
						<li>
							<span class="label">ISO</span>
							<span class="value">{{ exif.iso_speed_ratings }}</span>
						</li>
				  </koken:not>                    
          <koken:not empty="exif.metering_mode">
          	<li>
          		<span class="label">Meter Mode</span>
          		<span class="value">{{ exif.metering_mode }}</span>
          	</li>
          </koken:not>          
					<koken:not empty="exif.exposure">
						<li>
							<span class="label">Exposure</span>
							<span class="value">{{ exif.exposure }}</span>
						</li>
					</koken:not>
					<koken:not empty="exif.exposure_bias">
						<li>
							<span class="label">Exposure -/+</span>
							<span class="value">{{ exif.exposure_bias }}</span>
						</li>
					</koken:not>
					<koken:not empty="exif.exposure_mode">
						<li>
							<span class="label">Exposure Mode</span>
							<span class="value">{{ exif.exposure_mode }}</span>
						</li>
					</koken:not>         
          <koken:not empty="exif.white_balance">
          	<li>
          		<span class="label">White Balance</span>
          		<span class="value">{{ exif.white_balance }}</span>
          	</li>
          </koken:not>          
          <koken:not empty="iptc.copyright">
						<li>
							<span class="label">Copyright</span>
							<span class="value">{{ iptc.copyright }}</span>
						</li>
				  </koken:not>
				 	</ol> 
          
                              
    <!-- EXIF Accordian - end block -->
		</section>
		<input type="radio" name="exif-accordion" id="acc-close" />
	</nav>
  <!-- EXIF Accordian - end block END -->

			 	</section>

			</koken:exif>

		</koken:if>

```

There's a collapsing CSS section within the above snippet, but otherwise it a simple modification of the original Elementary theme's code with added values that were taken straight from Koken's docs.

Something I also noticed while prepping this post... there's no .htaccess or blank index.html files in any of the koken-created image folders to discourage folder browsing to scrape images. It would be really helpful if they were created on the initial image import and resizing.

For reference, here's copies of my 4 lens files for both the 'album' and 'content' types
[lumi-2_lens-files.zip](https://github.com/koken/issues/files/643924/lumi-2_lens-files.zip)

**Comment by humantex** [comment]
I saw something that I thought might be a possible fix and wanted to try it, but I still get the same results.

```
<koken:iptc>
      <koken:not empty="iptc.copyright">          
		<li>
			<span class="label">Copyright</span>
			<span class="value">{{ iptc.copyright }}</span>
		</li>            
	</koken:not>
</koken:iptc>
```

I thought it may have been me, by not surrounding the copyright bits with `<koken:iptc></koken:iptc>`

**Comment by MikeCostello** [comment]
@humantex can you try in v0.22.13. Changes to the EXIF & IPTC tags were made, that should help when used in duplicate. IDK if this is your use case.

**Comment by humantex** [comment]
I just looked at both my live site's displayed pages and the underlying theme code after the 22.13 update - but - still the same results. I also ran the update to my dev setup, with no change to the output.

Could you confirm something about the metadata itself... Is it reread directly from the image file being displayed on every single page load - or - is the data collected on upload and stored in the database to be read from there and displayed when the page is rendered?

I only ask to figure out if I need to redo any uploads to take advantage of the latest code changes.

The other EXIF changes worked great BTW.

**Comment by humantex** [comment]
After several rounds of trial and error I finally tracked down the issue. Apparently Koken doesn't like nested lens tags. In my case I had been trying to use the IPTC Copyright tag within the content rendered by the EXIF tag. Using koken:iptc in any form, or completely absent had no effect at all - whenever it was embedded within the otherwise-working exif section. I had to add a totally new block of iptc code below the closing of both koken:exif and koken:if to get it to display properly.

Code, as added:

```
..... other exif data displays above here....
<!-- EXIF Accordian - end block END -->

		</section>
		</koken:exif>
		</koken:if>
			<!-- separately added copyright block-->
				<koken:iptc>
				<koken:not empty="iptc.copyright">
						&nbsp;<br>
						<span class="label"></span>
						<span class="value">{{ iptc.copyright }}</span>
						<br>&nbsp;<br>
			  	</koken:not>
			  	</koken:iptc>
			<!-- end copyright block -->
		<koken:if true="settings.content_detail_show_cats">
```
![koken-copyright-fixed](https://cloud.githubusercontent.com/assets/16087649/21517204/0a68a244-ccab-11e6-8929-ecb1a0167f18.jpg)
