### ISSUE TITLE
Unable to open store in admin interface

### ISSUE THREAD

**Issue by Forecaster** [koken/issues#41]
Whenever I click the "Store" link on my sites admin page it just displays a white page with the store sidebar for a few seconds, then returns to the page I came from. It doesn't say why. There are no errors in the console either.

**Comment by MikeCostello** [comment]
I've confirmed the store is currently up and running, but please contact us via the [Help Center](http://help.koken.me/) and an agent will follow up with you. This repo is used for tracking code related issues.

**Comment by rgeorgi** [comment]
> I've confirmed the store is currently up and running, but please contact us via the [Help Center](http://help.koken.me/) and an agent will follow up with you. This repo is used for tracking code related issues.

I mean… As of March 2018, this is still broken. The store may be up, but trying to load it from the admin interface results in an infinite redirect loop.
