### ISSUE TITLE
koken:permalink broken inside a album

### ISSUE THREAD

**Issue by BlackSkorpio** [koken/issues#48]
When using `<koken:permalink />` in a album it's returning

* http://oxygen.local/albums/3b282123dd267b5b4c405b876de90f50/

When it should return

* http://oxygen.local/albums/scenery/

**Comment by BlackSkorpio** [comment]
The same goes for when calling `<koken:permalink />`in set.lens, it's returning

* http://oxygen.local/sets/231814452dfcbb8f4a7da5a0e64a2458/

When it should return

* http://oxygen.local/sets/nature/

**Comment by MikeCostello** [comment]
Tried adding `<koken:permalink />` to Elementary & OxyGen, both rendered the permalink in album and set templates. Could you try on a fresh install? Or provide additional steps.

**Comment by BlackSkorpio** [comment]
Closing this as it seams it's related to WAMP it self for some reason
On the remote site everything works as one would expect
