### ISSUE TITLE
koken:link ignores any class set that has -

### ISSUE THREAD

**Issue by BlackSkorpio** [koken/issues#49]
I.E `<koken:link class="o-myClass">Text</koken:link>`  the `o-myClass` is ignored/removed.
While `<koken:link class="o_myClass">Text</koken:link>` is accepted.

**Comment by MikeCostello** [comment]
Tried on Elementary theme with PHP 5.6 on the `content.lens` template. Hyphened class rendered ok. Can give additional info on issue.

**Comment by BlackSkorpio** [comment]
Once again, it's me, WAMP and JS that fooled me :/
