### ISSUE TITLE
Cart: Images not part of an album does not get the cart icon in timeline

### ISSUE THREAD

**Issue by BlackSkorpio** [koken/issues#52]
The whole thing can be seen here: https://varoystrand.se/kokenDEV/timeline/ 

Images 

* [Girl-1502394-Kopia](https://varoystrand.se/kokenDEV/timeline/#content-184)
* [En Ensam Boj](https://varoystrand.se/kokenDEV/timeline/#content-183)

Both are not part of any album

When viewing the same images via contents.lens they get the cart icon

Cart setting, is Images for purchase: All images

**Comment by MikeCostello** [comment]
fixed in Cart 1.1.6-beta.1
