### ISSUE TITLE
"Like" Buttons - no direct refresh & counting

### ISSUE THREAD

**Issue by ChristophCaina** [koken/issues#53]
Hello there,

I've noticed, that the User does not recognize, that his like was counted after he clicked the like-Button.
The Counter does only show the counts after a page refresh - which can be a bit disturbing for the visitor.

There should be a more dynamic way to interact with the User in this way - for example by using AJAX technologies.
You can visit my page for an example at: https://www.caina.de

**Comment by MikeCostello** [comment]
The Rating plugin should should respond with JSON and update w/o need for a refresh. Please submit a case at http://help.koken.me/customer/portal/emails/new providing Koken & FTP credentials so we can further troubleshoot the issue.
