### ISSUE TITLE
Impossible to manually add keywords/tags containing spaces

### ISSUE THREAD

**Issue by humantex** [koken/issues#57]
I just noticed this behavior on an image that I'd neglected to add some important keywords to before importing. This is repeatable in every instance. I just upgraded to 0.22.24, but I doubt if this issue is version-specific, as I've also just found some fragmented tags from earlier manual entries.

An example... I usually add a single keyword/tag value in whatever software or utility I'm processing with, for the model/variation of the legacy taking lens used in a photo when it won't show up in the camera-generated EXIF data. That text string will always contains spaces - i.e., **AF-S DX Nikkor 18-55mm f/3.5-5.6G VR**.

If the value was added before the import into Koken, I see it displayed with the value exactly as entered - with the spaces intact. If I try to manually add and assign a keyword/tag from the admin panel, it breaks the entire string up into separate bits - using the 'space' as a separator/delimiter.

The text string entered then turns into 6 individual tags - with each one showing in Koken's tag list as: 

- **af-s**
- **dx**
- **nikkor**
- **18-55mm**
- **f3.5-5.6g**
- **vr**

I tried to 'force' Koken's acceptance of spaces by using either commas or semicolons as separators and entering multiple keywords at the same time, but they were ignored. I expected the change to lower case, and the loss of the forward slash due to 'sanitizing' the string, but I don't want to end up with fragmented tags when Koken splits up it's manually entered tags at each space it encounters.

My only option was to delete the imported file, reprocess the image to enter the metadata in Photoshop - then import it again to show the correct keywords intact as a full string.

**Comment by Hard-One** [comment]
Just surround your tags with quotation marks. ;)

-----Original Message-----

**Comment by humantex** [comment]
Well that was something I would never had expected! And it does indeed preserve the spaces. Thanks Hard-One... I assume that makes it a 'feature' and not a bug. Ah well, I'll just have to remember it if I need to do the same thing again.
