### ISSUE TITLE
Absolute img URLs in slideshows and img paths

### ISSUE THREAD

**Issue by BlackSkorpio** [koken/issues#8]
I'm assuming you using something like:
`{{ location.site_url }}/{{content.filename }}`
When building the src url for images and slideshows

Replacing that with something like
`{{ location.root_folder }}/{{content.filename }}`

Would make life much easier for people serving the same site with multiple domains

**Comment by BlackSkorpio** [comment]
A note should be made that these absolute paths will/can also break a site when using SSL since it many times refers to the non-SSL site (When going from non-SSL to enforcing SSL via htaccess or even apache config).

**Comment by Hard-One** [comment]
Actually it is like you describe it. It is currently impossible to use SSL because those absolute paths always refer to http and not https.
I think this is essential especially for those considering using the cart plugin.

**Comment by Hard-One** [comment]
Manually deleting the cache folders did the trick to rebuild the urls for https on my site. But for all essays and pages one must re-puplish them in order to rebuild the urls inside them.  For sites with a lot of essays and pages this is not an option.

**Comment by BlackSkorpio** [comment]
Hi there @MikeCostello is there any progress done with this issue?

**Comment by MikeCostello** [comment]
Fixed in https://github.com/koken/koken/commit/9cddbf603b91f86fd28bd22bf7936bf9169601b3 v0.22.21-beta.5

**Comment by BlackSkorpio** [comment]
Looks good and solid, have it running on both sites right now; guess we can close this one then 👍
